# Generated by Django 5.1.2 on 2024-11-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicname', models.CharField(max_length=200)),
                ('musicvocalist', models.CharField(max_length=200)),
                ('musicimages', models.CharField(max_length=200)),
                ('albumname', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'musiclist',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
